include: 
  - application.yml
  - infrastructure.yml
  - monitoring.yml
  - seed.yml
  - tools.yml

volumes:
  # # dynamodb
  # dynamodb-data:
  # kafka
  kafka1-data:
  kafka2-data:
  kafka3-data:
  # monitoring
  grafana-data:
  prometheus-data:
  loki-data:
  promtail-data:
  # redis
  redis-cache-data:
  redis-pubsub-data:
  # tools
  redisinsight-data:

x-common-variables: &common-variables
  ENVIRONMENT: local
  LOG_LEVEL: info