services:
  # dynamodb:
  #   image: amazon/dynamodb-local:latest
  #   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
  #   working_dir: /home/dynamodblocal
  #   user: "1000:1000"
  #   volumes:
  #     - dynamodb-data:/home/dynamodblocal/data
  #   environment:
  #     AWS_ACCESS_KEY_ID: "dummy"
  #     AWS_SECRET_ACCESS_KEY: "dummy"
  #     AWS_REGION: "us-east-1"
  #   healthcheck:
  #     test: ["CMD-SHELL", '[ "$(curl -s -o /dev/null -I -w ''%{http_code}'' http://localhost:8000)" == "400" ]']
  #     interval: 5s
  #     timeout: 5s
  #     retries: 3

  kafka-1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-1
    container_name: kafka-1
    volumes:
      - kafka1-data:/var/lib/kafka/data
    env_file:
      - ../config/kafka/kafka-1.env
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka-1:29092 --list >/dev/null 2>&1"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 5s

  kafka-2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-2
    container_name: kafka-2
    volumes:
      - kafka2-data:/var/lib/kafka/data
    env_file:
      - ../config/kafka/kafka-2.env
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka-2:29092 --list >/dev/null 2>&1"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 5s

  kafka-3:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-3
    container_name: kafka-3
    volumes:
      - kafka3-data:/var/lib/kafka/data
    env_file:
      - ../config/kafka/kafka-3.env
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka-3:29092 --list >/dev/null 2>&1"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis-cache:
    image: redis:alpine
    ports:
      - "16379:6379"
    volumes:
      - ../config/redis/cache.conf:/usr/local/etc/redis/redis.conf
      - redis-cache-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-pubsub:
    image: redis:alpine
    ports:
      - "16380:6379"
    volumes:
      - ../config/redis/pubsub.conf:/usr/local/etc/redis/redis.conf
      - redis-pubsub-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
