services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "19090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    volumes:
      - ../config/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    ports:
      - "18000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ../config/grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    depends_on:
      prometheus:
        condition: service_healthy
      loki:
        condition: service_started

  loki:
    image: grafana/loki:latest
    ports:
      - "13100:3100"
    volumes:
      - ../config/loki/loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../config/promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
      - promtail-data:/tmp
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  kminion-exporter:
    image: redpandadata/kminion:v2.2.12
    volumes:
      - ../config/kminion/kminion.yml:/etc/kminion/config.yml
    environment:
      CONFIG_FILEPATH: /etc/kminion/config.yml
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy

  redis-exporter-cache:
    image: oliver006/redis_exporter:latest
    environment:
      - REDIS_ADDR=redis-cache:6379
    depends_on:
      - redis-cache

  redis-exporter-pubsub:
    image: oliver006/redis_exporter:latest
    environment:
      - REDIS_ADDR=redis-pubsub:6379
    depends_on:
      - redis-pubsub
