services:
  # dynamodb-admin:
  #   image: aaronshaf/dynamodb-admin:latest
  #   ports:
  #     - "18001:8001"
  #   environment:
  #     DYNAMO_ENDPOINT: "http://dynamodb:8000"
  #   depends_on:
  #     dynamodb:
  #       condition: service_healthy

  akhq:
    image: tchiotludo/akhq
    ports:
      - "18002:8080"
    volumes:
      - ../config/akhq/akhq.yml:/app/application.yml
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
    profiles:
      - optional
      - all

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "18003:5540"
    volumes:
      - redisinsight-data:/data
    depends_on:
      - redis-cache
      - redis-pubsub
    profiles:
      - optional
      - all
