services:
  go-service:
    build:
      context: ../../../apps/go-service
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ../../../apps/go-service:/app
    ports:
      - "13000:8080"
    environment:
      - KAFKA_BROKERS=kafka-1:29092,kafka-2:29092,kafka-3:29092
      - KAFKA_CONSUMER_GROUP=group-1
      - REDIS_ADDR=redis-pubsub:6379
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      redis-pubsub:
        condition: service_started

  elixir-service:
    build:
      context: ../../../apps/elixir_service
      dockerfile: Dockerfile
    volumes:
      - ../../../apps/elixir_service:/app
    ports:
      - "14000:4000"
    environment:
      - REDIS_URI=redis://default:@redis-pubsub:6379
    depends_on:
      - redis-pubsub