include: 
  - application.yml
  - redis.yml
  - kafka.yml
  - tools.yml

volumes:
  # redis
  redis-cache-data:
  redis-pubsub-data:
  # tools
  redisinsight-data:

x-common-variables: &common-variables
  ENVIRONMENT: local
  LOG_LEVEL: info