services:
  redis-cache:
    image: redis:alpine
    ports:
      - "16379:6379"
    volumes:
      - ../config/redis/cache.conf:/usr/local/etc/redis/redis.conf
      - redis-cache-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-pubsub:
    image: redis:alpine
    ports:
      - "16380:6379"
    volumes:
      - ../config/redis/pubsub.conf:/usr/local/etc/redis/redis.conf
      - redis-pubsub-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  kafka-1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-1
    container_name: kafka-1
    volumes:
      - kafka1-data:/var/lib/kafka/data
    env_file:
      - ../config/kafka/kafka-1.env
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka-1:29092 --list >/dev/null 2>&1"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 5s

  kafka-2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-2
    container_name: kafka-2
    volumes:
      - kafka2-data:/var/lib/kafka/data
    env_file:
      - ../config/kafka/kafka-2.env
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka-2:29092 --list >/dev/null 2>&1"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 5s

  kafka-3:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-3
    container_name: kafka-3
    volumes:
      - kafka3-data:/var/lib/kafka/data
    env_file:
      - ../config/kafka/kafka-3.env
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka-3:29092 --list >/dev/null 2>&1"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 5s

  kafka-init:
    image: confluentinc/cp-kafka:latest
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
    command: |
      /bin/bash -c '
      kafka-topics --bootstrap-server kafka-1:29092 --create --if-not-exists --topic market_data --partitions 3 --replication-factor 3 &&
      kafka-topics --bootstrap-server kafka-1:29092 --create --if-not-exists --topic trade_orders --partitions 3 --replication-factor 3 &&
      kafka-topics --bootstrap-server kafka-1:29092 --create --if-not-exists --topic trade_executed --partitions 3 --replication-factor 3
      '