services:
  kafka-1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-1
    container_name: kafka-1
    volumes:
      - kafka1-data:/var/lib/kafka/data
    env_file:
      - ../config/kafka/kafka-1.env
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka-1:29092 --list >/dev/null 2>&1"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 5s

  kafka-2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-2
    container_name: kafka-2
    volumes:
      - kafka2-data:/var/lib/kafka/data
    env_file:
      - ../config/kafka/kafka-2.env
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka-2:29092 --list >/dev/null 2>&1"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 5s

  kafka-3:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-3
    container_name: kafka-3
    volumes:
      - kafka3-data:/var/lib/kafka/data
    env_file:
      - ../config/kafka/kafka-3.env
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka-3:29092 --list >/dev/null 2>&1"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 5s
