services:
  redis-cache:
    image: redis:8.0-M04-alpine
    ports:
      - "16379:6379"
    volumes:
      - ../config/redis/cache.conf:/usr/local/etc/redis/redis.conf
      - redis-cache-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-pubsub:
    image: redis:8.0-M04-alpine
    ports:
      - "16380:6379"
    volumes:
      - ../config/redis/pubsub.conf:/usr/local/etc/redis/redis.conf
      - redis-pubsub-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
