services:
  akhq:
    image: tchiotludo/akhq
    ports:
      - "18001:8080"
    volumes:
      - ../config/akhq/akhq.yml:/app/application.yml
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "18002:5540"
    volumes:
      - redisinsight-data:/data
    depends_on:
      - redis-cache
      - redis-pubsub
