services:
  akhq:
    image: tchiotludo/akhq
    ports:
      - "18080:8080"
    volumes:
      - ../config/akhq/application.yml:/app/application.yml
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "18001:5540"
    volumes:
      - redisinsight-data:/data
    depends_on:
      - redis-cache
      - redis-pubsub
