services:
  akhq:
    image: tchiotludo/akhq
    ports:
      - "18080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local:
              properties:
                bootstrap.servers: "kafka:29092"
              topic-creation: true
    depends_on:
      - kafka

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "18001:5540"
    volumes:
      - redisinsight-data:/db
    depends_on:
      - redis-cache
      - redis-pubsub
