global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kminion-exporter:8080']
    metrics_path: /metrics

  - job_name: 'redis-cache'
    static_configs:
      - targets: ['redis-exporter-cache:9121']
    metrics_path: /metrics

  - job_name: 'redis-pubsub'
    static_configs:
      - targets: ['redis-exporter-pubsub:9121']
    metrics_path: /metrics